### ISSUE TITLE
#myTimeHasCome

### ISSUE THREAD

**Issue by pielco11** [twintproject/twint-zero#12]
![image](https://user-images.githubusercontent.com/17363750/233646171-d0a51a47-9f9d-4be1-9ec3-445f41d3c9b9.png)

as of now this tool doesn't because the bridge between Nitter and Twitter is broken.

I will add details here as time goes by.

\* heavy sad noise \*

**Comment by archy-bold** [comment]
Seems to be affecting most instances, but not all. I can use Twint with [this instance](https://nitter.simpleprivacy.fr/) for example.

**Comment by archy-bold** [comment]
Heh, looks like it's already fixed! https://github.com/zedeus/nitter/issues/840#issuecomment-1518021594

**Comment by zedeus** [comment]
Please don't scrape public Nitter instances, it's unethical and can cause a worse experience for people actually using them properly. Host your own on your computer/server, it takes a few seconds to set up with Docker and a few minutes at most without.

**Comment by pielco11** [comment]
@zedeus totally agree with you. I just added a line in the README doc

**Comment by DavidPerea** [comment]
Does this new variant of Twint still work?  I am a former Twint user who, after this tool no longer works, has searched for alternatives and I have come back to you.  However after reading these messages I don't know if this new tool is still working.

**Comment by archy-bold** [comment]
It's in a bit of a weird state. With the rapid changes Twitter has been making recently to try to cut off web scraping, Nitter (which this project relies on) is on-off working. Some instances are down because they're rate-limited, which this issue refers to. Although that issue has been fixed for instances that have updated. There was also a recent change that made search an authenticated-user-only action, effectively bringing down Nitter's search functionality unless you used a fork that added the ability to set an access token. But that seems to have been reversed, at least temporarily.

It's a cat and mouse game basically and is currently working. But for how long, nobody really knows.
