### ISSUE TITLE
Request to update documentation  && slight issue that I want to report (nothing too severe)

### ISSUE THREAD

**Issue by mystery-z** [twintproject/twint-zero#24]
### Request to Update Documentation
I was actually having a lot of problem trying to run this, because I couldn't tell if putting the quotation marks mattered or not. 

But I eventually got it to work, and I think it would be nice if we had a small section under "CLI Arguments" just to make this easier for people. 

It would be best named something like "Example usage" and it would be nice if you just added the following to the markdown:

Command:
```go run main.go -Query "from:Technothepig" -Instance "nitter.net" -Format "csv" > tweets.csv``` 

What it does:
 - scape all the tweets from [@Technothepig](https://twitter.com/technothepig)

### Slight issue that I found:
So instances of nitter have this feature where they replace all reddit links to teddit.net, and all youtube links to piped.video links:
<img width="643" alt="스크린샷 2023-08-20 오후 9 12 18" src="https://github.com/twintproject/twint-zero/assets/53719487/926d27b7-2b4a-45aa-9f36-598c539373d1">

While this is a good feature, I don't really want this to appear in the posts that I'm downloading, and there **doesn't seem to be any way to disable this from the CLI interface**, is there any way to fix this? If you think there is a way, I would be happy to help implement it!

**Comment by archy-bold** [comment]
As far as I'm aware Nitter handles settings on requests through cookies. I wrote something to enable HLS Video in order to get video URLs, you can find that code [here](https://github.com/twintproject/twint-zero/blob/62e33d209c75b34e324f69c5ee0c84d454cc9326/Core/Request.go#L20C22-L20C22). If you want to write something to override those settings, that would probably be a good place to start.

**Comment by pielco11** [comment]
Hi @mystery-z ,

apologies for the late reply.

As per your first point: this is about CLI arguments crafting, rather than parsing. To me it's an issue more about passing the value to the code, than having the value "analysed" and therefore correctly set.

Simply put: CLI arguments are in our control, not code's.

FAQ: Yeah, nice, thanks bro, but what does it cost to you to add just that line?
A: I'm worried we are talking about different things, Sir.



Coming to your second point: that is really what people mean by saying "that's a feature, not a bug". Still, I do agree that in certain situations that's a feature not requested and may actually cause issues. I'm not commenting on this.

I think it may be of help to have the possibility to specify to have the "native" domains or the "proxy" ones.
To me it sounds like a low-priority feature, therefore I'm worried to not have a dedicated spot to implement such a feature. If you may like to write it by yourself and open a PR, please feel more than open to proceed. Simon already provided you with some inputs


Best,
FP
