### ISSUE TITLE
Is command "since:2023-01-10" working ?

### ISSUE THREAD

**Issue by Ramizworking** [twintproject/twint-zero#3]
Hey boss ! Thank you for your amazing work

When I use

go run main.go -Query nasa since:2023-01-10

It still gives me tweet from January 09 or random times

Again when I use : 

go run main.go -Query nasa within:

go run main.go -Query tezos within_time:1d

I get tweets like made 3 months before or 5 months 

If you could bring a fix for that ?

Thank you so much !

**Comment by pielco11** [comment]
Hi,

I think there was an error on how inputs were parsed. May you can now, please? I see no errors on my end.

Thanks

**Comment by vivificationLeslie** [comment]
Hi I got same issue when I input:
go run main.go -Query "control AND adaptive" since:2022-12-02 until:2023-04-11 -Instance nitter.moomoo.me -Format csv > ControlAdaptive.csv
It returns the results from the last three months

**Comment by vivificationgq** [comment]
> Hi,
> 
> I think there was an error on how inputs were parsed. May you can now, please? I see no errors on my end.
> 
> Thanks

Hi I got same issue when I input:
`go run main.go -Query "control AND adaptive" since:2022-12-02 until:2023-04-11 -Instance nitter.moomoo.me -Format csv > ControlAdaptive.csv`
It returns  5140 results from the last three months.

And if I change the input:
` go run main.go -Query "adaptive AND control" since:2022-12-02 -Instance nitter.moomoo.me -Format csv > adaptivecontrol.csv `
It returns 1868 results from Sep 5, 2021

**Comment by archy-bold** [comment]
Your query is the issue, you've not put quotes around the full query, just the first part. You need to run the following command:

```bash
go run main.go -Query "control AND adaptive since:2022-12-02 until:2023-04-11" -Instance nitter.moomoo.me -Format csv
```

Note the position of the quotes.
